### ISSUE TITLE
[LinesCounter] Наименование!!!

### ISSUE THREAD

**Issue by pavel-b-novikov** [Tkachov/nsudotnet#4]
Да вы меня специально чтоли побесить решили? В одной задаче camelCase, в другой - underline_case для методов? Прочитайте еще раз гайдлайны по именованию, ну правда.

**Comment by Tkachov** [comment]
Эту задачу писал первой, ну и использовал underline по привычке.

В следующей уже стал писать camelCase, но гайдлайны прочитать не удосужился. Исправлю.
