### ISSUE TITLE
[LinesCounter] string.IsNullOrWhiteSpace

### ISSUE THREAD

**Issue by pavel-b-novikov** [Tkachov/nsudotnet#5]
В целом реализация задачи неплоха - это как раз то, что было нужно. Однако:

> string.IsNullOrWhiteSpace(line[i]+"")
> Чем обусловлено использование вот этого вот чуда техники? Кто вас научил?

**Comment by Tkachov** [comment]
Сначала вспомнить не мог, теперь догадался: line[i] — char, а string.IsNullOrWhiteSpace требовал string, ну вот таким нехитрым способом char превращается в string и всем хорошо.

**Comment by Tkachov** [comment]
Забавно, закрыть одно Issue гитхаб за меня смог, а подумать, что я мог два сразу исправить — нет.

**Comment by pavel-b-novikov** [comment]
на этот случае есть char.Is%Something%
Не делайте так в приличном обществе
