### ISSUE TITLE
[TicTacToe] ref Game game

### ISSUE THREAD

**Issue by pavel-b-novikov** [Tkachov/nsudotnet#6]
Откройте секрет мастеров кодинга - в чем необходимость передавать Game через ref? И чем отличается передача Game в метод с ref и без такового?

**Comment by Tkachov** [comment]
Я человек простой — вижу ссылки, ими и пользуюсь. В моих плюсах по ссылке не передашь, так сразу весь объект копироваться будет, а исходный объект не поменяется. Наверное, стоило сначала про ref прочитать, прежде чем использовать.

**Comment by pavel-b-novikov** [comment]
Вы знаете, этот принцип применим не только к ключевому слову ref, а вообще по жизни.
