### ISSUE TITLE
[TicTacToe] Проперти!!!

### ISSUE THREAD

**Issue by pavel-b-novikov** [Tkachov/nsudotnet#7]
> public bool xMove() { return X_move;  }

Ну прекращайте же вы писать геттеры и сеттеры руками. Узнайте наконец про механизм пропертей.

Далее - для getField/getFieldByPosition перегрузите индексатор (чтобы можно было через квадратные скобки обращаться к классу Game)

**Comment by Tkachov** [comment]
Про проперти знал, но забыл, как они пишутся, поэтому проще было геттер сделать.

Про перегрузку операторов даже не подумал, потому что я на C# давно не писал, и задачи писал фактически как будто на Java пишу (с какой-то другой стандартной библиотекой).

**Comment by pavel-b-novikov** [comment]
НЕ ЗАКРЫВАЙТЕ ISSUES САМИ БЛИН!

2016-05-06 0:44 GMT+06:00 Alexander notifications@github.com:

> Closed #7 https://github.com/Tkachov/nsudotnet/issues/7.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/Tkachov/nsudotnet/issues/7#event-651799394

## 

Sincerely yours,
Pavel B. Novikov
Skype: nsu_the_cjay
Phone: +7 961 872 5447

**Comment by Tkachov** [comment]
ОК. Они сами закрываются, кстати, если их рядом со словом fix в описании коммита указать.
