### ISSUE TITLE
[TicTacToe] Безграмотнейший StringBuilder

### ISSUE THREAD

**Issue by pavel-b-novikov** [Tkachov/nsudotnet#8]
Я правильно понимаю, что separator и cellSeparator создаются один раз и в целом никогда не меняются? Зачем вы их положили в StringBuilder? Просто строк вам мало?

А вот как раз вместо fieldLines не помешал бы StringBuilder. Кстати, а что мешает писать строки сразу же в консоль, без хранения оных в промежуточном массиве?

**Comment by Tkachov** [comment]
Первоначально у меня вообще было захардкожено поле для 3х3 (типа того, которое в комментарии нарисовано). А поскольку в задании сказано StringBuilder использовать, то там еще и через него это все делалось.

Разделители, действительно, можно и попроще задать.

А вот на консоль печатать строки без хранения в массиве сложно, потому что у меня этих массивов два, для левой и правой колонок, и жонглировать индексами, вычисляя, какой кусок левого большого поля будет соответствовать какому куску маленьких правых полей, мне не хотелось.

**Comment by Tkachov** [comment]
Я, собственно, только разделители строками обычными задал.

Индексами жонглировать я до сих пор не хочу, поэтому массивы никуда не делись, и я не уверен, чем бы здесь помог StringBuilder.

**Comment by pavel-b-novikov** [comment]
Слушайте, я что-то не вижу чтобы вы в этот массив строк писали по разным индексам или чтобы перетасовывали строки, по сему - не мелите чушь :) Вы можете сделать последовательный вывод на консоль/в sb последовательным вызовом Append/AppendLine. Я в вас верю.

**Comment by Tkachov** [comment]
Ну вот и посмотрите какой агрегат получился вместо стройного последовательного добавления строк в массивы. Чтобы понять, какую строку я печатаю в правой колонке, приходится сравнивать индекс текущей строки с множеством неочевидных значений.

Завтра кто-нибудь захочет добавить строку между двумя квадратиками в правой колонке, и вместо добавления одной (или нескольких, если еще отступ вокруг хочется добавить) строки кода придется не только добавить условие на соответствующий индекс, но и поменять во всей этой конструкции константы на +1 в тех строках, которые печатаются после той, которую мы добавили. Читать сложно, изменять сложно, профита по сути несколько байт.

**Comment by pavel-b-novikov** [comment]
Ладно. пусть будет по-вашему.
